layout_spectrum: 0.469534
color:
  saturation: 1
  brandStrength: 0.6855841
  lightness: 0.4928315
  rhythmicContrast: 0.749104
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.5788531
name: botox
